api/urls.py
from django.urls import path
from . import views

app_name ='api'

urlpatterns = [
    # CATEGORY API
    path('category/all', views.GetAllCategories),
    path('category/new', views.NewCategory),
    path('category/<str:slug>', views.SingleCategory),
    # PRODUCTS API
    path('products/all', views.ProductsList),
    path('products/new', views.NewProduct),
    path('products/<str:slug>', views.SingleProduct),
    # REVIEWS API
    path('reviews/update/<int:pk>', views.UpdateReview),
    path('reviews/delete/<int:pk>', views.DeleteReview),
    # SEARCH API
    path('Search', views.Search),
    # AUTH API
    path('users/changepassword', views.ChangePasswordView.as_view()),
    path('users/profile/<int:pk>', views.UserProfile.as_view()),
    path('users/user/delete', views.DeleteUser),
    path('users/user/<int:pk>', views.UserView.as_view()),
    path('users/signup', views.SignUp),
    # ORDER API
    path('checkout/order', views.OrderView.as_view()),
    path('checkout/order/<int:pk>', views.SingleOrder.as_view()),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add_to_cart/<str:slug>', views.add_to_cart, name='add_to_cart'),
    path('cart-details', views.cart_details, name='cart_details'),
    path('quantity-plus/<str:slug>', views.quantity_plus, name='quantity_plus'),
    path('quantity-minus/<str:slug>', views.quantity_minus, name='quantity_minus'),
    path('remove-from-cart/<str:slug>', views.remove_from_cart, name='remove_from_cart'),
    path('clear_cart', views.clear_cart, name='clear_cart'),
    path('place-order', views.place_order, name='place_order'),
    path('checkout', views.checkout, name='checkout'),
    path('order-history', views.OrderHistory, name='order_history'),
]

project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('pages.urls', namespace='pages')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.error_404_view'
handler500 = 'pages.views.error_500_view'

shop/urls.py
from django.urls import path
from . import views

app_name ='shop'

urlpatterns = [
    # CATEGORY URLS
    path('category', views.CategoryList.as_view(), name='category_list'),
    path('category/create', views.CategoryCreate.as_view(), name='category_create'),
    path('category/<str:slug>', views.CategoryDetail, name='category_detail'),
    path('category/update/<str:slug>', views.CategoryUpdate.as_view(), name='category_update'),
    path('category/delete/<str:slug>', views.CategoryDelet.as_view(), name='category_delet'),
    # PRODUCTS URLS
    path('search', views.Search, name='search'),
    path('products', views.ProductList.as_view(), name='product_list'),
    path('products/create', views.ProductCreate.as_view(), name='product_create'),
    path('products/<str:slug>', views.ProductDetail, name='product_detail'),
    path('products/update/<str:slug>', views.ProductUpdate.as_view(), name='product_update'),
    path('products/delete/<str:slug>', views.ProductDelete.as_view(), name='product_delete'),
    # WISHLIST URLS
    path('wishlist/<str:slug>', views.wishlist, name='product_wishlist'),
    path('wishlistview', views.WishListView, name='wishlist_view')
]

cart/models.py
from itertools import product
from django.db import models
from django.contrib.auth.models import User
from shop.models import Product
from phonenumber_field.modelfields import PhoneNumberField
from creditcards.models import CardNumberField, CardExpiryField, SecurityCodeField


STATUS_CHOICES =  (
    ('pending', 'pending'),
    ('onroad', 'onroad'),
    ('delivered', 'delivered'),
)

class Order(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.FloatField()
    discount = models.FloatField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    country = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    phone = PhoneNumberField()
    phoneTwo = PhoneNumberField(null=True, blank=True)
    status = models.CharField(choices=STATUS_CHOICES, max_length=10, default=STATUS_CHOICES[0])
    card_number = CardNumberField()
    expire = CardExpiryField()
    security_code = SecurityCodeField()

    def __str__(self):
        return f"order {self.pk}"
    
    def placeOrder(self):
        self.save()
    
    @staticmethod
    def get_orders_by_customer(customer):
        return Order.objects.filter(customer = customer)

cart/views.py
from itertools import product
from django.shortcuts import render, redirect
from django.urls import reverse
from shop.models import Product
from django.contrib import messages
from .models import Order
from django.contrib.auth.decorators import login_required


def add_to_cart(request, slug):
    product = Product.objects.get(slug=slug)
    cart = request.session.get('cart')
    sucees_message = "product added successfully to cart"
    if cart:
        quantity = cart.get(product.slug)
        if quantity:
            cart[product.slug] += 1
            messages.success(request, sucees_message)
        else:
            cart[product.slug] = 1
            messages.success(request, sucees_message)
    else:
        cart = {}
        cart[product.slug] = 1
        messages.success(request, sucees_message)
    request.session['cart'] = cart
    return redirect(reverse('shop:product_detail', kwargs={'slug':product.slug}))


def cart_details(request):
    products = None
    if request.session.get('cart'):
        slugs = list(request.session.get('cart').keys())
        products = Product.get_products_by_slug(slugs)
    return render(request, 'cart/cart_details.html', {'products':products})


def quantity_plus(request, slug):
    product_slug = request.POST.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart = request.session.get('cart')
    if cart:
        quantity = cart.get(product.slug)
        if quantity:
            cart[product.slug] += 1
    request.session['cart'] = cart
    return redirect(reverse('cart:cart_details'))


def quantity_minus(request, slug):
    product_slug = request.POST.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart = request.session.get('cart')
    if cart:
        quantity = cart.get(product.slug)
        if quantity > 1:
            cart[product.slug] -= 1
        else:
            del cart[product.slug]
    request.session['cart'] = cart
    return redirect(reverse('cart:cart_details'))


def remove_from_cart(request, slug):
    product_slug = request.POST.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart = request.session.get('cart')
    if cart:
        del cart[product.slug]
    request.session['cart'] = cart
    return redirect(reverse('cart:cart_details'))


def clear_cart(request):
    cart = request.session.get('cart')
    if cart:
        cart.clear()
    request.session['cart'] = cart
    return redirect(reverse('cart:cart_details'))


@login_required
def place_order(request):
    cart = request.session.get('cart')
    if cart:
        return render(request, 'cart/place_order.html', {})
    else:
        return redirect('shop:product_list')


@login_required
def checkout(request):
    if request.method == 'POST':
        country = request.POST.get('country')
        city = request.POST.get('city')
        address = request.POST.get('address')
        phone = request.POST.get('phone')
        phoneTwo = request.POST.get('phoneTwo')
        card_number = request.POST.get('cardNumber')
        expire = request.POST.get('expire')
        security_code = request.POST.get('securityCode')
        customer = request.user
        cart = request.session.get('cart')
        products = Product.get_products_by_slug(list(cart.keys()))

        for product in products:
            if product.discount != None:
                discount = product.discount
            else:
                discount = 0
            order = Order(
                country = country,
                city = city,
                address = address,
                phone = phone,
                phoneTwo = phoneTwo,
                card_number = card_number,
                expire = expire,
                security_code = security_code,
                customer = customer,
                price = product.price - discount,
                product = product,
                quantity = cart.get(str(product.slug))
            )
            order.placeOrder()
        request.session['cart'] = {}
    return redirect('shop:product_list')


@login_required
def OrderHistory(request):
    customer = request.user
    orders = Order.get_orders_by_customer(customer)
    return render(request, 'cart/order-history.html', {'orders': orders})

templates/cart/cart_details.html
{% extends 'base.html' %}
{% block body %}
{% load cart %}
    <section>
        <div class="container">
            {% if request.session.cart %}
            <h1 class="main-heading text-center">your shopping cart</h1>
            <table>
                <tr>
                    <th>product</th>
                    <th>image</th>
                    <th>price</th>
                    <th>discount</th>
                    <th>quantity</th>
                    <th>total price</th>
                    <th>delete</th>
                </tr>
                {% for product in products %}
                    <tr>
                        <td>
                            {{product}}
                        </td>
                        <td class="img-row"><img src="{{product.image.url}}"></td>
                        <td>{{product.price}} $</td>
                        <td>
                            {% if product.discount %}
                                {{ product.discount }}
                            {% else %}
                                0
                            {% endif %}
                        </td>
                        <td>
                            <!-- QUANTITY MINUS -->
                            <form class="quantity-form" action="{% url 'cart:quantity_minus' product.slug %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="product_slug" value="{{product.slug}}">
                                <button class="quantity-button">-</button>
                            </form>
                            <!-- QUANTITY -->
                            {{product|cart_quantity:request.session.cart}}
                            <!-- QUANTITY PLUS -->
                            <form class="quantity-form" action="{% url 'cart:quantity_plus' product.slug %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="product_slug" value="{{product.slug}}">
                                <button class="quantity-button">+</button>
                            </form>
                        </td>
                        <td>{{product|total_price:request.session.cart}} $</td>
                        <td>
                            <form title="Remove {{product}}" action="{% url 'cart:remove_from_cart' product.slug %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="product_slug" value="{{product.slug}}">
                                <button type="submit" class="delete">
                                    <i class="fas fa-trash-alt fa-fw"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
                <tfooter>
                    <th class="total-price" colspan="5">total price</th>
                    <th>{{products|total_cart_price:request.session.cart}} $</th>
                    <td>
                        <form title="Remove All" action="{% url 'cart:clear_cart' %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="delete">
                                <i class="fas fa-trash-alt fa-fw"></i>
                            </button>
                        </form>
                    </td>
                </tfooter>
            </table>
            <div class="checkout-card">
                <a class="checkout-button" href="{% url 'cart:place_order' %}">checkout</a>
            </div>
            {% else %}
                <h1 class="main-heading text-center">your shopping cart is empty now</h1>
                <div class="continue-shopping">
                    <a href="{% url 'shop:product_list' %}">continue shopping</a>
                </div>
            {% endif %}
        </div>
    </section>
{% endblock body %}

templates/cart/order-history.html
{% extends 'base.html' %}
{% block body %}
{% load cart %}
    <section>
        <div class="container">
            {% if orders %}
                <h1 class="text-center">your orders history</h1>
                <table>
                    <tr>
                        <th>product</th>
                        <th>image</th>
                        <th>price</th>
                        <th>quantity</th>
                        <th>total price</th>
                        <th>status</th>
                    </tr>
                    {% for order in orders %}
                        <tr>
                            <td>{{order.product}}</td>
                            <td class="img-row"><img src="{{order.product.image.url}}"></td>
                            <td>{{order.price}} $</td>
                            <td>{{order.quantity}}</td>
                            <td>{{order.quantity|order_total_price:order.price}}</td>
                            <td> {{order.status}} </td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <h1 class="text-center">no orders yet</h1>
            {% endif %}
        </div>
    </section>
{% endblock body %}

templates/cart/place_order.html
{% extends 'base.html' %}
{% block body %}
<section>
    <div class="container">
        <div class="form-center">
            <form class="my-form md" method="POST" action="{% url 'cart:checkout' %}">
                {% csrf_token %}
                <label for="country">country</label>
                <input type="text" name="country" id="country" required>
                <label for="city">city</label>
                <input type="text" name="city" id="city" required>
                <label for="address">address</label>
                <input type="text" name="address" id="address" required>
                <label for="phone">phone</label>
                <input type="tel" name="phone" id="phone" required>
                <label for="phoneTwo">phone 2 (optional)</label>
                <input type="tel" name="phoneTwo" id="phoneTwo">
                <label for="cardNumber">card number</label>
                <input type="text" name="cardNumber" id="cardNumber" placeholder="2424 2424 2424 2424" required>
                <label for="expire">expire</label>
                <input type="text" name="expire" id="expire" placeholder="mm/yy" required>
                <label for="securityCode">security code</label>
                <input type="text" name="securityCode" id="securityCode" placeholder="333" required>
                <button type="submit" style="margin-top:20px">submit</button>
            </form>
        </div>
    </div>
</section>
{% endblock body %}