api/urls.py
from django.urls import path
from . import views

app_name ='api'

urlpatterns = [
    # CATEGORY API
    path('category/all', views.GetAllCategories),
    path('category/new', views.NewCategory),
    path('category/<str:slug>', views.SingleCategory),
    # PRODUCTS API
    path('products/all', views.ProductsList),
    path('products/new', views.NewProduct),
    path('products/<str:slug>', views.SingleProduct),
    # REVIEWS API
    path('reviews/update/<int:pk>', views.UpdateReview),
    path('reviews/delete/<int:pk>', views.DeleteReview),
    # SEARCH API
    path('Search', views.Search),
    # AUTH API
    path('users/changepassword', views.ChangePasswordView.as_view()),
    path('users/profile/<int:pk>', views.UserProfile.as_view()),
    path('users/user/delete', views.DeleteUser),
    path('users/user/<int:pk>', views.UserView.as_view()),
    path('users/signup', views.SignUp),
    # ORDER API
    path('checkout/order', views.OrderView.as_view()),
    path('checkout/order/<int:pk>', views.SingleOrder.as_view()),
]

project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('pages.urls', namespace='pages')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.error_404_view'
handler500 = 'pages.views.error_500_view'

shop/urls.py
from django.urls import path
from . import views

app_name ='shop'

urlpatterns = [
    # CATEGORY URLS
    path('category', views.CategoryList.as_view(), name='category_list'),
    path('category/create', views.CategoryCreate.as_view(), name='category_create'),
    path('category/<str:slug>', views.CategoryDetail, name='category_detail'),
    path('category/update/<str:slug>', views.CategoryUpdate.as_view(), name='category_update'),
    path('category/delete/<str:slug>', views.CategoryDelet.as_view(), name='category_delet'),
    # PRODUCTS URLS
    path('search', views.Search, name='search'),
    path('products', views.ProductList.as_view(), name='product_list'),
    path('products/create', views.ProductCreate.as_view(), name='product_create'),
    path('products/<str:slug>', views.ProductDetail, name='product_detail'),
    path('products/update/<str:slug>', views.ProductUpdate.as_view(), name='product_update'),
    path('products/delete/<str:slug>', views.ProductDelete.as_view(), name='product_delete'),
    # WISHLIST URLS
    path('wishlist/<str:slug>', views.wishlist, name='product_wishlist'),
    path('wishlistview', views.WishListView, name='wishlist_view')
]

templates/pages/about.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
    <div class="home">
        <div class="container-fluid">
            <div class="cover">
                <img src="{% static 'img/virender-singh-hE0nmTffKtM-unsplash.jpg' %}" >
                <div class="cover-text">
                    <h1>mega market</h1>
                    <h2>every thing that's new and now</h2>
                    <a href="{% url 'shop:product_list' %}">shop now</a>
                </div>
            </div>
        </div>
    </div>
    <section>
        <div class="container">
            <h1>who we are</h1>
            <p>
                Lorem ipsum dolor sit amet,
                consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
                nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
                mollit anim id est laborum.
            </p>
            <p>
                Lorem ipsum dolor sit amet,
                consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
                nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
                mollit anim id est laborum.
            </p>
            <p>
                Lorem ipsum dolor sit amet,
                consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
                nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
                mollit anim id est laborum.
            </p>
        </div>
    </section>
{% endblock body %}

templates/pages/home.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
<div class="home">
    <div class="container-fluid">
        <div class="cover">
            <img src="{% static 'img/virender-singh-hE0nmTffKtM-unsplash.jpg' %}" >
            <div class="cover-text">
                <h1>mega market</h1>
                <h2>every thing that's new and now</h2>
                <a href="{% url 'shop:product_list' %}">shop now</a>
            </div>
        </div>
    </div>
    <section>
        <div class="container-fluid">
            <div class="categories">
                {% for category in categories %}
                    <div class="category">
                        <a href="{% url 'shop:category_detail' category.slug %}">
                            <div class="category-heading">
                                <h2 class="text-center">{{ category }}</h2>
                            </div>
                            <div class="category-img">
                                <img src="{{ category.image.url }}">
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <h1 class="text-center main-heading">new on mega</h1>
            <div class="products">
                {% for product in products %}
                    <a href="{% url 'shop:product_detail' product.slug %}" class="product">
                        <div class="product-main">
                            <img src="{{ product.image.url }}">
                            <div class="product-features">
                                {% if product.discount %}
                                    <span class="text-center sale">sale !</span>
                                {% endif %}
                                {% if product.is_BestSeller == True %}
                                    <span class="text-center bestseller">bestseller</span>
                                {% endif %}
                                {% if product.is_featured == True %}
                                    <span class="text-center featured">featured</span>
                                {% endif %}
                                {% if product.is_valid == False %}
                                    <span class="text-center soldout">sold out</span>
                                {% endif %}
                            </div>
                        </div>
                        <div class="product-info">
                          <div class="product-heading">
                              <h2 class="text-center">{{ product }}</h2>
                          </div>
                          <div class="product-price">
                              {{ product.get_price }} $
                              {% if product.discount %}
                                 <span class="discount"><del>{{ product.price }} $</del><span>
                              {% endif %}
                          </div>
                        </div>
                    </a>
                {% endfor %}
            </div>
            <div class="view-all">
                <a href="{% url 'shop:product_list' %}">view all products</a>
            </div>
        </div>
    </section>
</div>
{% endblock body %}

templates/pages/not_found.html
{% extends 'base.html' %}
{% block body %}
<section>
  <div class="container">
    <div class="not-found">
      <h1 class="text-center">404</h1>
      <p class="text-center">oops! pages not found</p>
      <div class="link-center">
        <a href="/">take me home</a>
      </div>
    </div>
  </div>
</section>
{% endblock body %}

templates/pages/server_internal_error.html
{% extends 'base.html' %}
{% block body %}
<section>
  <div class="container">
    <div class="not-found">
      <h1 class="text-center">500</h1>
      <h1 class="text-center">server internal error</h1>
      <p class="text-center">we're experiencing an internal server error please try again later</p>
    </div>
  </div>
</section>
{% endblock body %}