accounts/urls.py
from django.urls import path
from . import views

app_name ='accounts'

urlpatterns = [
    path('profile/<int:pk>', views.UserProfile.as_view(), name='profile'),
    path('profile/update/<int:pk>', views.UpdateProfile.as_view(), name='update_profile'),
    path('profile/delete/<int:pk>', views.delete_user, name='delete_user'),
    path('signup', views.signup, name='signup'),
]

api/urls.py
from django.urls import path
from . import views

app_name ='api'

urlpatterns = [
    # CATEGORY API
    path('category/all', views.GetAllCategories),
    path('category/new', views.NewCategory),
    path('category/<str:slug>', views.SingleCategory),
    # PRODUCTS API
    path('products/all', views.ProductsList),
    path('products/new', views.NewProduct),
    path('products/<str:slug>', views.SingleProduct),
    # REVIEWS API
    path('reviews/update/<int:pk>', views.UpdateReview),
    path('reviews/delete/<int:pk>', views.DeleteReview),
    # SEARCH API
    path('Search', views.Search),
    # AUTH API
    path('users/changepassword', views.ChangePasswordView.as_view()),
    path('users/profile/<int:pk>', views.UserProfile.as_view()),
    path('users/user/delete', views.DeleteUser),
    path('users/user/<int:pk>', views.UserView.as_view()),
    path('users/signup', views.SignUp),
    # ORDER API
    path('checkout/order', views.OrderView.as_view()),
    path('checkout/order/<int:pk>', views.SingleOrder.as_view()),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add_to_cart/<str:slug>', views.add_to_cart, name='add_to_cart'),
    path('cart-details', views.cart_details, name='cart_details'),
    path('quantity-plus/<str:slug>', views.quantity_plus, name='quantity_plus'),
    path('quantity-minus/<str:slug>', views.quantity_minus, name='quantity_minus'),
    path('remove-from-cart/<str:slug>', views.remove_from_cart, name='remove_from_cart'),
    path('clear_cart', views.clear_cart, name='clear_cart'),
    path('place-order', views.place_order, name='place_order'),
    path('checkout', views.checkout, name='checkout'),
    path('order-history', views.OrderHistory, name='order_history'),
]

project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('pages.urls', namespace='pages')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.error_404_view'
handler500 = 'pages.views.error_500_view'

shop/urls.py
from django.urls import path
from . import views

app_name ='shop'

urlpatterns = [
    # CATEGORY URLS
    path('category', views.CategoryList.as_view(), name='category_list'),
    path('category/create', views.CategoryCreate.as_view(), name='category_create'),
    path('category/<str:slug>', views.CategoryDetail, name='category_detail'),
    path('category/update/<str:slug>', views.CategoryUpdate.as_view(), name='category_update'),
    path('category/delete/<str:slug>', views.CategoryDelet.as_view(), name='category_delet'),
    # PRODUCTS URLS
    path('search', views.Search, name='search'),
    path('products', views.ProductList.as_view(), name='product_list'),
    path('products/create', views.ProductCreate.as_view(), name='product_create'),
    path('products/<str:slug>', views.ProductDetail, name='product_detail'),
    path('products/update/<str:slug>', views.ProductUpdate.as_view(), name='product_update'),
    path('products/delete/<str:slug>', views.ProductDelete.as_view(), name='product_delete'),
    # WISHLIST URLS
    path('wishlist/<str:slug>', views.wishlist, name='product_wishlist'),
    path('wishlistview', views.WishListView, name='wishlist_view')
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.dispatch import receiver
from django.urls import reverse
from ckeditor.fields import RichTextField
import os



class Category(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='category/')
    slug = models.SlugField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True, null=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product,self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category,self).save(*args, **kwargs)

    def __str__(self):
        return self.name


@receiver(models.signals.post_delete, sender=Category)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """ DELETE CATEGORY IMAGE AUTOMATICALLY FROM MEDIA AFTER DELETEING CATEGORY """
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)


@receiver(models.signals.pre_save, sender=Category)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """ DELETE CATEGORY IMAGE AUTOMATICALLY FROM MEDIA AFTER UPDATING CATEGORY """
    if not instance.pk:
        return False
    try:
        old_file = Category.objects.get(pk=instance.pk).image
    except Category.DoesNotExist:
        return False
    new_file = instance.image
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)

class Product(models.Model):
    name = models.CharField(max_length=255)
    description = RichTextField()
    image = models.ImageField(upload_to='products/')
    price = models.FloatField()
    discount = models.FloatField(null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    in_stock = models.PositiveIntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, related_name='product_category',null=True, blank=True)
    is_valid = models.BooleanField(default=True)
    is_BestSeller = models.BooleanField(default=False)
    is_featured = models.BooleanField(default=False)
    wished = models.ManyToManyField(User, related_name='favourite')
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product,self).save(*args, **kwargs)

    def get_price(self):
        if self.discount != None:
            return self.price - self.discount
        else:
            return self.price

    def get_discount_percent(self):
        discount_percent = round((self.discount/self.price) * 100)
        return f"{discount_percent}% off"

    def get_absolute_url(self):
        return reverse('shop:product_detail', kwargs={'slug':self.slug})

    @staticmethod
    def get_products_by_slug(slugs):
        return Product.objects.filter(slug__in = slugs)

    def __str__(self):
        return self.name


@receiver(models.signals.post_delete, sender=Product)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """ DELETE PRODUCT IMAGE AUTOMATICALLY FROM MEDIA AFTER DELETEING PRODUCT """
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)


@receiver(models.signals.pre_save, sender=Product)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """ DELETE PRODUCT IMAGE AUTOMATICALLY FROM MEDIA AFTER UPDATING PRODUCT """
    if not instance.pk:
        return False
    try:
        old_file = Product.objects.get(pk=instance.pk).image
    except Product.DoesNotExist:
        return False
    new_file = instance.image
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)


class WishList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return str(f"{self.user} liked {self.product}")


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    comment = models.TextField()
    rate = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user} review on {self.product}"

shop/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['comment', 'rate']

shop/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.db.models import Avg
from .models import Category, Product, Review
from .forms import ReviewForm


#### CATEGORY VIEWS
class CategoryList(ListView):
    model = Category
    ordering = ['-id']


def CategoryDetail(request, slug):
    try:
        category = Category.objects.get(slug=slug)
    except Category.DoesNotExist:
        raise Http404
    product = Product.objects.filter(category=category)
    return render(request, 'shop/category_detail.html', {'category':category, 'products':product})


class CategoryCreate(LoginRequiredMixin, CreateView):
    model = Category
    fields = ['name', 'image']

    def get_success_url(self):
        return reverse('shop:category_list')


class CategoryUpdate(LoginRequiredMixin, UpdateView):
    model = Category
    fields = ['name', 'image']

    def get_success_url(self):
        return reverse('shop:category_list')


class CategoryDelet(DeleteView):
    model = Category

    def get_success_url(self):
        return reverse('shop:category_list')


#### PRODUCT VIEWS
class ProductList(ListView):
    model = Product
    ordering = '-last_update'
    paginate_by = 9
    def get_context_data(self, **kwargs):
        context = super(ProductList, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


def Search(request):
    product = None
    # SEARCH RESUTL
    if 'search' in request.GET:
        name = request.GET['search']
        if name:
            product = Product.objects.filter(name__icontains=name)
    return render(request, 'shop/search.html', {'products':product,'name':name})


def ProductDetail(request, slug):
    try:
        product = Product.objects.get(slug=slug)
    except Product.DoesNotExist:
        raise Http404
    related_products = Product.objects.filter(category=product.category).order_by('-last_update').exclude(id=product.id)[:3]
    other_products = Product.objects.filter(owner=product.owner).order_by('-last_update').exclude(id=product.id)[:3]
    reviews = Review.objects.filter(product=product.id).order_by('-created_at')
    reviews_count = reviews.count()
    reviews_avg = reviews.aggregate(Avg("rate"))["rate__avg"]
    if reviews_avg != None:
        reviews_avg = round(reviews.aggregate(Avg("rate"))["rate__avg"], 1)

    # REVIEW FORM
    if request.method == 'POST':
        review_form = ReviewForm(request.POST or None)
        if review_form.is_valid():
            content = request.POST.get('comment')
            rate = request.POST.get('rate')
            review = Review.objects.create(product = product, user = request.user, rate=rate ,comment = content)
            review.save()
            return HttpResponseRedirect(product.get_absolute_url())
    else:
        review_form = ReviewForm()

    context = {
        'product':product,
        'related_products':related_products,
        'other_products':other_products,
        'reviews':reviews,
        'review_form':review_form,
        'reviews_count':reviews_count,
        'reviews_avg':reviews_avg
    }
    return render(request, 'shop/product_detail.html', context)


class ProductCreate(LoginRequiredMixin, CreateView):
    model = Product
    fields = ['name', 'description', 'image', 'price', 'discount', 'in_stock', 'category', 'is_valid']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('shop:product_list')


class ProductUpdate(LoginRequiredMixin, UpdateView):
    model = Product
    fields = ['name', 'description', 'image', 'price', 'discount', 'in_stock', 'category', 'is_valid']
    template_name = 'shop/product_update.html'

    def get_success_url(self):
        return reverse('shop:product_list')


class ProductDelete(LoginRequiredMixin, DeleteView):
    model = Product

    def get_success_url(self):
        return reverse('shop:product_list')


@login_required
def wishlist(request, slug):
    user = request.user
    product = Product.objects.get(slug=slug)
    if request.method == 'POST':
        if user in product.wished.all():
            product.wished.remove(user)
        else:
            product.wished.add(user)
    return redirect(reverse('shop:product_detail', kwargs={"slug": product.slug}))


@login_required
def WishListView(request):
    product = Product.objects.filter(wished=request.user)
    return render(request, 'shop/wishlist.html', {'products':product})

templates/shop/category_confirm_delete.html
{% extends 'base.html' %}
{% block body %}
        <section>
            <div class="container">
                {% if request.user.is_staff %}
                <h1 class="text-center">are you sure you want to delte category {{category.name}} ?</h1>
                <form method="POST" class="my-form">
                    {% csrf_token %}
                    <div class="confirm">
                        <button type="submit">delete</button>
                        <button type=button value="cancel" class="cancel" onClick="javascript:history.go(-1);">cancel</button>
                    </div>
                </form>
                {% else %}
                    <h1 class="text-center">sorry! you aren't allowed here</h1>
                {% endif %}
            </div>
        </section>
{% endblock body %}

templates/shop/category_detail.html
{% extends 'base.html' %}
{% block body %}
    <section>
        <div class="container">
            <h1 class="text-center main-heading">{{category}}</h1>
            <div class="products">
                {% for product in products %}
                    <a href="{% url 'shop:product_detail' product.slug %}" class="product">
                        <div class="product-main">
                            <img src="{{ product.image.url }}">
                            <div class="product-features">
                                {% if product.discount %}
                                    <span class="text-center sale">sale !</span>
                                {% endif %}
                                {% if product.is_BestSeller == True %}
                                    <span class="text-center bestseller">bestseller</span>
                                {% endif %}
                                {% if product.is_featured == True %}
                                    <span class="text-center featured">featured</span>
                                {% endif %}
                                {% if product.is_valid == False %}
                                    <span class="text-center soldout">sold out</span>
                                {% endif %}
                            </div>
                        </div>
                        <div class="product-info">
                          <div class="product-heading">
                              <h2 class="text-center">{{ product }}</h2>
                          </div>
                          <div class="product-price">
                              {{ product.get_price }} $
                              {% if product.discount %}
                                 <span class="discount"><del>{{ product.price }} $</del><span>
                              {% endif %}
                          </div>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock body %}

templates/shop/category_form.html
{% extends 'base.html' %}
{% block body %}
    {% comment %}
        ONLY STAFF CAN CREATE NEW CATEGORIES
    {% endcomment %}
    <section>
        <div class="container">
            {% if request.user.is_staff %}
                <h1 class="text-center">create new category</h1>
                <form method="POST" enctype="multipart/form-data" class="my-form">
                    {{form.as_ul}}
                    {% csrf_token %}
                    <button type="submit">post</button>
                </form>
            {% else %}
                <h1 class="text-center">sorry! you arren't allowed here</h1>
            {% endif %}
        </div>
    </section>
{% endblock body %}

templates/shop/category_list.html
{% extends 'base.html' %}
{% block body %}
    <section>
        <div class="container">
            {% if request.user.is_staff %}
                <a class="add" href="{% url 'shop:category_create' %}">
                    <i class="fa fa-plus fa-fw"></i> add category
                </a>
            {% endif %}
            <h1 class="main-heading text-center">category list</h1>
            <div class="categories">
                {% for category in category_list %}
                    <div class="category">
                        <a href="{% url 'shop:category_detail' category.slug %}">
                            <div class="category-heading">
                                <h2 class="text-center">{{ category }}</h2>
                            </div>
                            <div class="category-img">
                                <img src="{{ category.image.url }}" loading="lazy"">
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock body %}

templates/shop/product_confirm_delete.html
{% extends 'base.html' %}
{% block body %}
        <section>
            <div class="container">
                {% if request.user == product.owner %}
                    <h1 class="text-center">are you sure you want to delte category {{product}} ?</h1>
                    <form method="POST" class="my-form">
                        {% csrf_token %}
                        <div class="confirm">
                            <button type="submit">delete</button>
                            <button type=button value="cancel" class="cancel" onClick="javascript:history.go(-1);">cancel</button>
                        </div>
                    </form>
                {% else %}
                    <h1 class="text-center">sorry! you aren't allowed here</h1>
                {% endif %}
            </div>
        </section>
{% endblock body %}

templates/shop/product_form.html
{% extends 'base.html' %}
{% block body %}
    <section>
        <div class="container">
            {% if user.profile.shop %}
                {% if user.profile.is_shop_verified == False %}
                    <h1 class="text-center">your shop is waiting to be verified by admins</h1>
                {% else %}
                    <h1 class="text-center">sell your product</h1>
                    <form method="POST" enctype="multipart/form-data" class="my-form">
                        {% csrf_token %}
                        {{form.media}}
                        {{form.as_ul}}
                        <button type="submit">post</button>
                        <input type=button value="cancel" class="cancel" onClick="javascript:history.go(-1);">
                    </form>
                {% endif %}
            {% else %}
                <h1 class="text-center">create your shop first</h1>
                <div class="center">
                    <a class="text-center" href="{% url 'accounts:update_profile' user.profile.id %}">create shop</a>
                    <input type=button value="cancel" class="cancel" onClick="javascript:history.go(-1);">
                </div>
           {% endif %}
        </div>
    </section>
{% endblock body %}

templates/shop/product_list.html
{% extends 'base.html' %}
{% block body %}
  <div class="product-list-container">
    <div class="product-list-side">
        <div class="category">
            <h2>categories</h2>
            {% for category in categories %}
                <li><a href="{% url 'shop:category_detail' category.slug %}">{{category}}</a></li>
            {% endfor %}
        </div>
    </div>
    <div class="product-list-main">
      <section>
          <div class="container">
              <h1 class="text-center main-heading">products</h1>
              <div class="products">
                  {% for product in product_list %}
                    <a href="{% url 'shop:product_detail' product.slug %}" class="product">
                        <div class="product-main">
                            <img src="{{ product.image.url }}" loading="lazy">
                            <div class="product-features">
                                {% if product.discount %}
                                    <span class="text-center sale">sale !</span>
                                {% endif %}
                                {% if product.is_BestSeller == True %}
                                    <span class="text-center bestseller">bestseller</span>
                                {% endif %}
                                {% if product.is_featured == True %}
                                    <span class="text-center featured">featured</span>
                                {% endif %}
                                {% if product.is_valid == False %}
                                    <span class="text-center soldout">sold out</span>
                                {% endif %}
                            </div>
                        </div>
                        <div class="product-info">
                        <div class="product-heading">
                            <h2 class="text-center">{{ product }}</h2>
                        </div>
                        <div class="product-price">
                            {{ product.get_price }} $
                            {% if product.discount %}
                                <span class="discount"><del>{{ product.price }} $</del><span>
                            {% endif %}
                        </div>
                        </div>
                    </a>
                  {% endfor %}
              </div>

              <!--========== PAGINATION ==========-->
              {% if page_obj.has_other_pages %}
                  <div class="pagination">
                      {% if page_obj.has_previous %}
                          <span class="page-item">
                              <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                                  <span aria-hidden="true">&laquo;</span>
                                  <span class="sr-only">Previous</span>
                              </a>
                          </span>
                      {% endif %}
                      {% for page in page_obj.paginator.page_range %}
                          <span><a class="page-link" href="?page={{page}}">{{page}}</a></span>
                      {% endfor %}
                      {% if page_obj.has_next %}
                          <span class="page-item">
                              <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                  <span aria-hidden="true">&raquo;</span>
                                  <span class="sr-only">Next</span>
                              </a>
                          </span>
                      {% endif %}
                  </div>
              {% endif %}

          </div>
      </section>
    </div>
  </div>
{% endblock body %}

templates/shop/product_update.html
{% extends 'base.html' %}
{% block body %}
    <section>
        <div class="container">
            {% if request.user == product.owner %}
                <h1>create new product</h1>
                <form method="POST" enctype="multipart/form-data" class="my-form">
                    {{form.media}}
                    {{form.as_ul}}
                    {% csrf_token %}
                    <button type="submit">post</button>
                </form>
            {% else %}
                <h1>sorry! you aren't allowed here</h1>
            {% endif %}
        </div>
    </section>
{% endblock body %}

templates/shop/search.html
{% extends 'base.html' %}
{% block body %}
    <section>
        <div class="container">
            {% if name %}
            <h1 class="text-center main-heading">searched products</h1>
            <div class="products">
                {% for product in products %}
                  <a href="{% url 'shop:product_detail' product.slug %}" class="product">
                      <div class="product-main">
                          <img src="{{ product.image.url }}">
                          <div class="product-features">
                              {% if product.discount %}
                                  <span class="text-center sale">sale !</span>
                              {% endif %}
                              {% if product.is_BestSeller == True %}
                                  <span class="text-center bestseller">bestseller</span>
                              {% endif %}
                              {% if product.is_featured == True %}
                                  <span class="text-center featured">featured</span>
                              {% endif %}
                              {% if product.is_valid == False %}
                                  <span class="text-center soldout">sold out</span>
                              {% endif %}
                          </div>
                      </div>
                      <div class="product-info">
                        <div class="product-heading">
                            <h2 class="text-center">{{ product }}</h2>
                        </div>
                        <div class="product-price">
                            {{ product.get_price }} $
                            {% if product.discount %}
                               <span class="discount"><del>{{ product.price }} $</del><span>
                            {% endif %}
                        </div>
                      </div>
                  </a>
                {% endfor %}
            </div>
            {% else %}
                <h1 class="text-center main-heading">no results to view</h1>
            {% endif %}
        </div>
    </section>
{% endblock body %}

templates/shop/wishlist.html
{% extends 'base.html' %}
{% block body %}
    <section>
        <div class="container">
            {% if products %}
                <h1 class="text-center main-heading">wishlist</h1>
                <table>
                    <tr>
                        <th>product</th>
                        <th>image</th>
                        <th>price</th>
                        <th>stock status</th>
                        <th>add to cart</th>
                    </tr>
                    {% for product in products %}
                        <tr>
                            <td>
                                <a href="{% url 'shop:product_detail' product.slug %}">
                                    {{product}}
                                </a>
                            </td>
                            <td class="img-row"><img src="{{product.image.url}}"></td>
                            <td>{{product.get_price}}$</td>
                            {% if product.is_valid == True %}
                                <td>
                                    <span class="success">in stock</span>
                                </td>
                            {% else %}
                                <td>
                                    <span class="danger">sold out</span>
                                </td>
                            {% endif %}
                            <td>
                                <form action="{% url 'cart:add_to_cart' product.slug %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="product_slug" value="{{product.slug}}">
                                    <button class="btn-cart"><i class="fas fa-shopping-cart fa-fw"></i></button>
                                </from>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <h1 class="text-center">no products added to your wishlist yet</h1>
            {% endif %}
        </div>
    </section>
{% endblock body %}