accounts/urls.py
from django.urls import path
from . import views

app_name ='accounts'

urlpatterns = [
    path('profile/<int:pk>', views.UserProfile.as_view(), name='profile'),
    path('profile/update/<int:pk>', views.UpdateProfile.as_view(), name='update_profile'),
    path('profile/delete/<int:pk>', views.delete_user, name='delete_user'),
    path('signup', views.signup, name='signup'),
]

api/urls.py
from django.urls import path
from . import views

app_name ='api'

urlpatterns = [
    # CATEGORY API
    path('category/all', views.GetAllCategories),
    path('category/new', views.NewCategory),
    path('category/<str:slug>', views.SingleCategory),
    # PRODUCTS API
    path('products/all', views.ProductsList),
    path('products/new', views.NewProduct),
    path('products/<str:slug>', views.SingleProduct),
    # REVIEWS API
    path('reviews/update/<int:pk>', views.UpdateReview),
    path('reviews/delete/<int:pk>', views.DeleteReview),
    # SEARCH API
    path('Search', views.Search),
    # AUTH API
    path('users/changepassword', views.ChangePasswordView.as_view()),
    path('users/profile/<int:pk>', views.UserProfile.as_view()),
    path('users/user/delete', views.DeleteUser),
    path('users/user/<int:pk>', views.UserView.as_view()),
    path('users/signup', views.SignUp),
    # ORDER API
    path('checkout/order', views.OrderView.as_view()),
    path('checkout/order/<int:pk>', views.SingleOrder.as_view()),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add_to_cart/<str:slug>', views.add_to_cart, name='add_to_cart'),
    path('cart-details', views.cart_details, name='cart_details'),
    path('quantity-plus/<str:slug>', views.quantity_plus, name='quantity_plus'),
    path('quantity-minus/<str:slug>', views.quantity_minus, name='quantity_minus'),
    path('remove-from-cart/<str:slug>', views.remove_from_cart, name='remove_from_cart'),
    path('clear_cart', views.clear_cart, name='clear_cart'),
    path('place-order', views.place_order, name='place_order'),
    path('checkout', views.checkout, name='checkout'),
    path('order-history', views.OrderHistory, name='order_history'),
]

pages/urls.py
from . import views
from django.urls import path

app_name = 'pages'

urlpatterns = [
    path('', views.home, name='home_page'),
    path('about', views.about, name='about_view'),
]

project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('pages.urls', namespace='pages')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.error_404_view'
handler500 = 'pages.views.error_500_view'

shop/urls.py
from django.urls import path
from . import views

app_name ='shop'

urlpatterns = [
    # CATEGORY URLS
    path('category', views.CategoryList.as_view(), name='category_list'),
    path('category/create', views.CategoryCreate.as_view(), name='category_create'),
    path('category/<str:slug>', views.CategoryDetail, name='category_detail'),
    path('category/update/<str:slug>', views.CategoryUpdate.as_view(), name='category_update'),
    path('category/delete/<str:slug>', views.CategoryDelet.as_view(), name='category_delet'),
    # PRODUCTS URLS
    path('search', views.Search, name='search'),
    path('products', views.ProductList.as_view(), name='product_list'),
    path('products/create', views.ProductCreate.as_view(), name='product_create'),
    path('products/<str:slug>', views.ProductDetail, name='product_detail'),
    path('products/update/<str:slug>', views.ProductUpdate.as_view(), name='product_update'),
    path('products/delete/<str:slug>', views.ProductDelete.as_view(), name='product_delete'),
    # WISHLIST URLS
    path('wishlist/<str:slug>', views.wishlist, name='product_wishlist'),
    path('wishlistview', views.WishListView, name='wishlist_view')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawsome/fontawsomefiles/all.min.css' %}">
	  <link rel="stylesheet" href="{% static 'css/fontawsome/fontawsomefiles/fontawsome.min.css' %}">
    <link rel="icon" href="{% static 'img/304843.png' %}">
    <title>mega</title>
</head>
<body>
    <header class="header">
        <nav class="navbar">
            <a href="/" class="nav-logo nav-logo-view">Mega</a>
              <ul class="nav-menu">
                  <a href="/" class="nav-logo nav-logo-lg">Mega</a>
                  <div class="links-container">
                      <li class="nav-item">
                          <a href="/" class="nav-link">home</a>
                      </li>
                      <li class="nav-item">
                          <a href="{% url 'pages:about_view' %}" class="nav-link">about</a>
                      </li>
                      <li class="nav-item">
                          <a href="{% url 'shop:product_list' %}" class="nav-link">products</a>
                      </li>
                      <li class="nav-item">
                          <a href="{% url 'shop:category_list' %}" class="nav-link">categories</a>
                      </li>
                      <li class="nav-item">
                          <a href="{% url 'shop:product_create' %}" class="nav-link">sell on mega</a>
                      </li>
                  </div>
                  <div class="links-container">
                      <li class="nav-item">
                          <span class="nav-link btn" id="search-button"><i class="fas fa-search fa-fw"></i></span>
                      </li>
                      {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <span class="nav-link btn user-btn">
                              <i class="fas fa-user fa-fw"></i>
                              <ul class="user-menu">
                                <li><a href="/accounts/login">login</a></li>
                                <li><a href="{% url 'accounts:signup' %}">register</a></li>
                              </ul>
                            </span>
                        </li>
                      {% else %}
                        <li class="nav-item">
                            <span class="nav-link btn user-btn">
                              {% if user.profile.image %}
                                <img 
                                    src="{{user.profile.image.url}}"
                                    class="nav-user-img"
                                >
                              {% else %}
                                <img 
                                    src="{% static 'img/default-user-image.png' %}"
                                    class="nav-user-img"
                                >
                              {% endif %}
                              <ul class="user-menu">
                                <li><a href="{% url 'accounts:profile' request.user.id %}">profile</a></li>
                                <li><a href="{% url 'cart:order_history' %}">order history</a></li>
                                <li><a href="/accounts/logout">logout</a></li>
                              </ul>
                            </span>
                        </li>
                      {% endif %}
                      <li class="nav-item">
                          <a href="{% url 'shop:wishlist_view' %}" class="nav-link btn">
                              <i class="far fa-heart fa-fw"></i>
                          </a>
                      </li>
                      <li class="nav-item">
                          <a href="{% url 'cart:cart_details' %}" class="nav-link btn">
                              <i class="fa fa-shopping-cart fa-fw"></i>
                              {% if request.session.cart|length > 0 %}
                                  {{ request.session.cart|length }}
                              {% endif %}
                          </a>
                      </li>
                  </div>
              </ul>
            <div class="hamburger">
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
            </div>
        </nav>
        <div class="search-form" id="search-form">
            <div class="container">
                <form class="my-form" action="{% url 'shop:search' %}">
                    <input type="text" placeholder="search" name="search">
                    <button><i class="fas fa-search"></i></button>
                    <div class="search-close btn" id="search-close">
                        <span class="bar"></span>
                        <span class="bar"></span>
                    </div>
                </form>
            </div>
        </div>
    </header>
    <main>
        {% block body %}
        {% endblock body %}
    </main>
    <footer>
        <div class="container">
            <div class="footer-sec info">
                <h1>mega</h1>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                    aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </p>
            </div>
            <div class="footer-sec">
                <ul>
                    <h1>links</h1>
                    <li><a href="/">home</a></li>
                    <li><a href="{% url 'pages:about_view' %}">about</a></li>
                    <li><a href="{% url 'shop:product_list' %}">products</a></li>
                    <li><a href="{% url 'shop:category_list' %}">categories</a></li>
                </ul>
            </div>
            <div class="footer-sec">
                <ul>
                    <h1>follow us</h1>
                    <li>
                      <a href="https://www.facebook.com/profile.php?id=100008372922486" target="_blank">
                        <i class="fab fa-facebook"></i>
                      </a>
                    </li>
                    <li>
                      <a href="https://github.com/emadElnagar" target="_blank">
                        <i class="fab fa-github"></i>
                      </a>
                    </li>
                    <li>
                      <a href="https://www.linkedin.com/in/emad-elnagar-23456022b/" target="_blank">
                        <i class="fab fa-linkedin"></i>
                      </a>
                    </li>
                </ul>
            </div>
        </div>
    </footer>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>